%%
dims.name = {'자기 관련도', '긍정', '부정', '중요도', '관계성', '중심성', '과거', '현재', '미래', ...
    '빈도', '안전', '위협', '시각적 형상', '텍스트성', '강도/세기', '구체성/선명도', '추상정/관념성', ...
    '자발성', '목표'};
dims.msg = {'이 생각은 나와 관련이 있다.', '이 생각은 나에게 중요하다.', '이 생각은 나의 자아정체감에 핵심적이다', ...
    '이 생각은 다른 사람들과 관련이 있다.', '이 생각은 과거 시점과 관련이 있다.', '이 생각은 현재 시점과 관련이 있다.', ...
    '이 생각은 미래 시점과 관련이 있다.', '최근에 이 생각이 자주 들었다.', '이 생각에 대한 나의 감정은 긍정적이다.', ...
    '이 생각에 대한 나의 감정은 부정적이다.', '이 생각은 나에게 안전감을 준다.', '이 생각은 나에게 위협감을 준다.', ...
    '이 생각은 시각적 이미지로 떠오른다.', '이 생각은 글의 형태로 떠오른다.', '이 생각에 대한 나의 감정은..', ...
    '이 생각은 구체적이고 선명하다.', '이 생각은 추상적이고 관념적이다.', '이 생각은 자연스럽게 떠올랐다.', '이 생각은 특정 목표를 이루는 것과 관련이 있다.'};

anchor = {'매우\n그렇다', '전혀\n아니다', '매우 강함', '매우 약함'};

save('dims_anchor_korean.mat', 'dims', 'anchor');

%%
dims.name = {'self-relevance', 'importance/value', 'centrality', 'social', 'past', 'present', 'future' ...
    'frequency', 'positive', 'negetive', 'safe', 'threat', 'imagery', 'word', 'intensity', 'detail(vivid)', ...
    'abstract', 'spontaneous', 'deliberate(goal)'};
dims.msg = { 'I consider this thought to be highly self-relevant.', ...
    'The topic of this thought is of great value or importance to me.', ...
'This thought contributes to my sense of self-identity.', ...
'My thoughts involved other people.', 'My thoughts involved past events.', ...
'My thoughts involved present events.', 'My thoughts involved future events.', ...
'Lately, it seems that this thought has been on my mind a great deal.', ...
'My own emotions pertaining to this thought are positive.', ...
'My own emotions pertaining to this thought are negative.', ...
'My own emotions pertaining to this thought are safe.', ...
'My own emotions pertaining to this thought are dangerous.', ...
'My thoughts were in the form of images.', 'My thoughts were in the form of words.', ...
'The intensity of my emotions pertaining to this thought are ...', ...
'My thoughts were specific and detailed or vivid.', ...
'My thoughts were abstract and conceptual.', 'My thoughts were spontaneous.', ...
'This thought involves/involved reaching a particular goal of mine.'};

anchor = {'Very\nmuch', 'Not\nat all', 'Very\nstrong', 'Very\nweak'};

save('dims_anchor_english.mat', 'dims', 'anchor');
